[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
gas_reports = ["Marketplace"]

remappings = ["@openzeppelin/=node_modules/@openzeppelin/","@chainlink/=node_modules/@chainlink/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config